Integration branch for visual studio fixes and SAML login
checkmarx-ltd/VisualStudio pull request #23
Opened 2022-06-28 14:45 UTC by jyotibhalerao

Code changes for below points:
1)Authentication fix that impacted hosted customers.
2)Additional log messages.
3)Fix for PLUG-513 - Results browsing and not being able to see CxPath, CxGraph.
4)Not able to install VS2022 plugin on VS 2022 version lower than 17.0.1.
5)The flag that enabled lib64 zip.
6)Support for complex solution (For ex. Open Web site code directly without a solution or scanning a folder of a solution).
7)Unbind so that if user open another solution closing the current one, bind the operation will work successfully.
8)Saml login.

2022-06-29 04:36 UTC, SubhadraSahoo requested changes
I have reviewed once. But you can ask Umesh also review once . Some places I see added code itself commented. Remove them.

2022-07-06 10:54 UTC, cx-umesh-waghode approved these changes
Looks good. QA cycle completed.

2022-07-06 10:55 UTC, cx-umesh-waghode approved these changes

2022-07-06 11:07 UTC, SubhadraSahoo approved these changes
Looks good

2022-07-06 11:08 UTC, merged